#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
markdown:         redcarpet
highlighter:      pygments
name: GeoSn0w

# Short bio or description (displayed in the header)
description: Programmer. Hacking stuff. Failed ordinary man.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/GeoSn0w/geosn0w.github.io/master/images/geosn0w-logo-small.jpg

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: office@fce365.info
  facebook: #Fuck facebook and their private data sucking policies.
  flickr:
  github: GeoSn0w
  instagram:
  linkedin:
  pinterest:
  rss: geosn0w
  twitter: FCE365
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: channel/UCAc5-CySN7SKYiNPznLIflQ
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-130435430-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://geosn0w.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
plugins:
   - ih8jekylltitles
theme: jekyll-theme-hacker
